# Public mirror dependency policy for cargo-deny.
# This is advisory validation for public engineering transparency.
# Final license and registry-submission review still requires legal review.

[advisories]
version = 2
yanked = "warn"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Zlib",
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
