apiVersion: 1

datasources:
  - name: clickhouse-1c
    uid: clickhouse-1c
    type: grafana-clickhouse-datasource
    access: proxy
    editable: true
    jsonData:
      defaultDatabase: analytics_1c
      port: 8123
      server: clickhouse
      protocol: http
      username: ${CLICKHOUSE_USER}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
