[package]
name = "merge-aw-server-dbs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
rusqlite = { workspace = true, features = ["backup"] }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
