[package]
name = "awatch-agent-rs"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_RemoteDesktop"] }

[dev-dependencies]
tempfile.workspace = true

[features]
default = []
asm-lowlevel = []
legacy-powershell = []
